### ISSUE TITLE
incorrect classification

### ISSUE THREAD

**Issue by vpol** [saffsd/langid.py#30]
written in russian, so correct
```
>>> langid.classify('пожалуйста')
('ru', 0.9189426432579942)
```
written in russian, so incorrect
```
>>> langid.classify('пример текста на русском')
('sr', 0.9431929502384854)
```
written in russian, so incorrect
```
>>> langid.classify('вомбат')
('uk', 0.4581717399240493)
```
written in hebrew, so incorrect
```
>>> langid.classify('וְאָהַבְתָּ אֵת יְיָ | אֱלֹהֶיךָ, בְּכָל-לְבָֽבְךָ, וּבְכָל-נַפְשְׁךָ, וּבְכָל-מְאֹדֶֽךָ. וְהָיוּ הַדְּבָרִים הָאֵלֶּה, אֲשֶׁר | אָֽנֹכִי מְצַוְּ')
('ko', 1.0)
```
written in old english, so incorrect (not sure that this example is correct)
```
>>> langid.classify(' On þyssum geare man halgode þet mynster æt Westmynstre on Cyldamæsse dæg 7 se cyng Eadward forðferde on Twelfts mæsse æfen 7 hine mann bebyrgede on Twelftan')
('is', 0.9999936552704334)
```

**Comment by saffsd** [comment]
Hi Victor,

Thanks for reporting the issue. I've reproduced and confirmed it on my end.
Unfortunately this isn't an easy one to tackle, as the model makes the best
guess it can based on the training data it has available. Because of the
way we downsample the patterns used to identify each language, what is
likely happening in this case is that each of the inputs you provide only
contains one or two patterns that are are actually used by langid.py. In
the middle case those patterns were more common in Serbian than Russian in
our training data, and in the last case they were (marginally) more common
in Ukrainian.

Depending on your intended use case, here are some possible workarounds:

1) If you're willing to assume only certain languages will be present, use
the (-l) flag to list those languages:

    $ python langid.py -l en,ru,it,de,fr -n
    >>> langid.classify('пожалуйста')
    ('ru', 1.0)
    >>> langid.classify('пример текста на русском')
    ('ru', 1.0)
    >>> langid.classify('вомбат')
    ('ru', 1.0)


2) If you have more than single words available, accuracy improves with
input length.

3) if you have a collection of documents in your target languages
available, langid.py can be re-trained with new training data.

If you give me a bit more information about your use case I can perhaps
give more specific suggestions.

Cheers,
Marco
